name: build

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
          contents: write
    steps:
      # Step 1.1: 检出代码并初始化子模块
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true  # 初始化子模块

      # Step 1.2 : 运行补丁脚本
      - name: Patch
        run: ./patch.sh

      # Step 2.1: 安装 meson 和 ninja
      - name: Install meson and ninja
        run: pip install meson ninja

      # Step 2.2: 设置 Go 环境
      - name: Set up Go
        uses: actions/setup-go@v5

      # Step 2.3 set TagName
      - name: Set env
        run: echo "TAG_NAME=$(echo $GITHUB_REF | sed 's/refs\/tags\///')" >> $GITHUB_ENV

      # Step 3: 设置 Android NDK 环境
      - name: Set up Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r27c

      # Step 4.1: 配置交叉编译环境变量并构建 Android 各平台二进制文件
      - name: Build arm64-v8a
        run: ./build.sh arm64-v8a $TAG_NAME

      # Step 4.2: 构建 Android x86_64 二进制文件
      - name: Build x86_64
        run: ./build.sh x86_64 $TAG_NAME

      # Step 5: 上传构建产物
      - name: Upload Android binaries
        uses: actions/upload-artifact@v4
        with:
          name: magisk-rclone
          if-no-files-found: error
          path: "*.zip"

      # Step 6: 如果有 tag，上传构建产物到现有 Release
      - name: Upload binaries to existing Release
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # 上传zip文件
          gh release upload "$TAG_NAME" *.zip --clobber
          # 上传 update.json 文件
          gh release upload "$TAG_NAME" update*.json --clobber



